input {
    # 'latam' es el código estándar para Latinoamérica
    kb_layout = latam
    
    # Dejar vacíos para evitar conflictos con los widgets de la barra
    kb_variant = 
    kb_model = 
    kb_options = 
    
    # Indispensable para tus cálculos de ingeniería
    numlock_by_default = true

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
    }
}

